version: '3'
services:
#mssql docker
  cookbook-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - cookbooknet

  cookbook-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Cookbook=Server=cookbook-sql,1433;Database=cookbook_prod;User=sa;Password=QWElkj132!
    ports:
      - 53404:80
    networks:
      - cookbooknet      
    links:
      - cookbook-sql
    depends_on:
      - cookbook-sql
      
networks:
  cookbooknet:
    driver: bridge   